config/routes.rb
DoeEye::Application.routes.draw do
	mount API => '/'

  devise_for :admins
  resources :document_types
  resources :vendors do
    resources :projects
  end

  root to: "vendor#index"
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/authorization.rb
class Authorization 
	include Mongoid::Document
	include Mongoid::Timestamps

	field :access_token
	field :expires_at
	
	before_create :generate_access_token
	before_create :set_expiration

	belongs_to :vendor

	def	set_expiration
		self.expires_at = DateTime.now+30
	end

	def	generate_access_token
		self.access_token = SecureRandom.hex
	end
end

app/models/document.rb
class Document
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :file, FileUploader

  field :title
  field :file  
  belongs_to :project
  has_one :document_type

  validates_presence_of :title
end

app/models/document_type.rb
class DocumentType
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  belongs_to :document
  
  validates_presence_of :name
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name

  belongs_to :vendor
  has_many :documents
  validates_presence_of :name
end

app/models/token.rb
class Token
	include Mongoid::Document
	include Mongoid::Timestamps

	field :access_token
	field :expires_at
	
	belongs_to :vendor
	before_create :generate_access_token
	before_create :set_expiration

	def	set_expiration
		self.expires_at = DateTime.now+30
	end

	def	generate_access_token
		self.access_token = SecureRandom.hex
	end
end

app/models/vendor.rb
class Vendor
  attr_accessor :api_password
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :api_key
  field :api_password_salt
  field :api_password_hash
  
  has_many :authorizations
  has_many :projects

  validates_presence_of :name, :api_key

  before_save :encrypt_password

  def encrypt_password
    if api_password.present?
      self.api_password_salt = BCrypt::Engine.generate_salt
      self.api_password_hash = BCrypt::Engine.hash_secret(api_password, api_password_salt)
    end
  end

  def self.authenticate(api_key, api_password)
    vendor = Vendor.where(api_key: api_key).first
    if vendor && vendor.api_password_hash == BCrypt::Engine.hash_secret(api_password, vendor.api_password_salt)
      vendor
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    vendors_path
  end
end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController
  
  before_filter :authenticate_admin!

  def new
    @document_type = DocumentType.new
  end
  
  def create
    @document_type = DocumentType.create(document_type_params)
    if @document_type.save!
      redirect_to document_type_path(@document_type)
    else
      render 'new' 
    end
  end


  def show
    @document_type = DocumentType.find(params[:id])
  end

  def document_type_params
    params.require(:document_type).permit(:name)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authenticate_admin!

  def new
    @project = Project.new
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  
  before_filter :authenticate_admin!
  
  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.create(vendor_params)
    if @vendor.save!
      redirect_to vendor_path(@vendor)
    else
      render 'new' 
    end
  end
  
  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])

    if @vendor.update(vendor_params)
      redirect_to vendor_path(@vendor)
    else
      render "edit"
    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(:name, :api_key, :api_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/document_types/new.html.haml
= form_for @document_type, html: { class: "form-horizontal" } do |f|
  %fieldset
    %legend New Vendor 
    .control-group
      = f.label :name, class: "control-label"
      .controls
        = f.text_field :name
    .control-group
      .controls
        = f.submit "Save", class: "btn btn-success"

app/views/document_types/show.html.haml
= @document_type.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoeEye</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Doe Eye Administration</a>
          <div class="navbar-text pull-right">
            <% if admin_signed_in? %>
              Logged in as: <%= current_admin.email %>
           	 <% end %>
        </div>
       </div>
      </div>
    </div>
	
    <div class="container-fluid">
			
      <div class="row-fluid">
					 <% if admin_signed_in? %>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><%= link_to "Vendors", vendors_path %></li>
            </ul>
          </div>
        </div>
		 <% end %>
        <div class="span9">
          <%= yield %>
        </div>	
      </div>	
    </div>
  </body>
</html>

app/views/vendors/edit.html.haml
= form_for @vendor do |f|
  = f.text_field :name
  = f.text_field :api_key
  = f.text_field :api_password
  = f.submit "Submit"

app/views/vendors/index.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th
        Name
      %th
        Actions
  %tbody
    - @vendors.each do |vendor|
      %tr
        %td
          = link_to vendor.name, vendor_path(vendor)
        %td
          = link_to "Edit", edit_vendor_path(vendor), class: "btn btn-warning btn-mini"
          = link_to "Delete", vendor_path(vendor), class: "btn btn-danger btn-mini"
    

app/views/vendors/new.html.haml
= form_for @vendor, html: { class: "form-horizontal" } do |f|
  %fieldset
    %legend New Vendor 
    .control-group
      = f.label :name, class: "control-label"
      .controls
        = f.text_field :name
    .control-group
      = f.label :api_key, class: "control-label"
      .controls
        = f.text_field :api_key
    .control-group
      = f.label :api_password, class: "control-label"
      .controls
        = f.text_field :api_password
    .control-group
      .controls
        = f.submit "Submit", class: "btn btn-success"

app/views/vendors/show.html.haml
%table.table.table-bordered
  %tr
    %td
      Name
    %td
      = @vendor.name
  %tr
    %td
      API Key
    %td
      = @vendor.api_key